spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hs-spring-security
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging.level:
  root: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE